### ISSUE TITLE
Decouple ReactiveUI and ReactiveUI events

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1043]
# The Plan

The package `reactiveui-events` is used in the platform specific unit test runner apps. Cannot progress CI builds until this dependency is unlinked. Here's the plan:

- [x] local `reactiveui-events` removed from all solutions.
- [x] eventbuilder xplat.
- [x] all `msbuild/mdtool` prebuild steps :fire:
- [x] :fire: any notion of VS or XS project (ie.. iOS64.csproj and iOS64_XS.csproj)
- [x] :fire: iOS legacy (non unified)
- [x] Rename iOS64 to iOS
- [x] :fire: Mac legacy (non unified)
- [x] :fire: WinRT 8.0
- [x] Build solution for `reactiveui-events` created.
- [x] Solution building for Xamarin iOS (latest)
- [x] Solution building for Xamarin Android (latest)
- [x] Solution building for Xamarin Mac (latest)
- [x] Solution building for Xamarin Forms (latest)
- [x] Solution building for Windows Forms
- [x] Solution building for Windows Store (WPA/RT)
- [x] Solution building for Windows Presentation Framework
- [x] Solution building for Windows Universal
- [x] Solution building for Windows Phone 8.x (WPA)
- [x] Solution building for Windows Phone 8.x (Silverlight)
- [x] Publish packages to MyGet feed.
- [x] Update all platform test runner applications to use the package MyGet feed.
- [x] Always ensure latest version of Xamarin iOS is used.
- [x] Always ensure latest version of Xamarin Android is used.
- [x] Always ensure latest version of Xamarin Mac is used.
- [x] Always ensure latest version of Xamarin Forms is used.
- [x] Create monthly job to republish the events on a schedule OR find a way to cause dependency trigger builds (ie.. new XF package = new Events build)
- [x] Start publishing/promoting packages to NuGet.
- [x] Resolve https://github.com/reactiveui/ReactiveUI/issues/1011 by excluding Windows metadata files.

# Background

The package `ReactiveUI-Events` (EventBuilder) does not depend on RxUI at all and RxUI does not depend on it either.  **edit** it's used in the platform specific unit test runner (i.e. iOS.app) **edit**

EventBuilder is essentially a giant xplat Observable from EventHandler helper library at the core, depending on which platform it is executed on it will generate a different library / set of Observable from EventHandlers.

EventBuilder has different versioning and release requirements than ReactiveUI - mainly the packages need to be regenerated when there are new API's that need surfacing  i.e. new iOS/Droid/UWP/Xamarin.Forms release.

Doing so would also allow us to simply the RxUI build story and get rid of the msbuild & ruby pre-build steps which are not x-plat.

/cc @moswald @gluck @kentcb for further comment.

> rxui-events has lots of potential outside its current scope, e.g. I use it to generate events wrapper for DevExpress Winforms & WPF libraries

Related #1006

**Comment by ghuntley** [comment]
# Misc Notes

› cd /Developer

at Geoffreys-MacBook-Pro.local in /Developer/
› ls -al
total 4
drwxr-xr-x  4 root     wheel  136 Nov 19 22:51 ./
drwxr-xr-x 34 root     wheel 1224 Jan 15 22:37 ../
lrwxr-xr-x  1 root     wheel   64 Nov 19 22:51 MonoAndroid -> ../Library/Frameworks/Xamarin.Android.framework/Versions/Current/
drwxr-xr-x  5 ghuntley staff  170 Jan 15 22:37 MonoTouch/


# Todo
 [x] Define convention for build output "Events.cs" vs "Events_Android.cs"
        Always use Events_$platform.cs

 [ ] Update csprojs to use the include convention.
 [ ] When "Xamarin Forms" is selected we also include Profile78 as a cheap and dirty hack, this may no longer be the correct profile. Speak with Oro.

    Profile 259 (.NET 4.5, Windows 8.0, Windows Phone Silverlight 8.0, Windows Phone 8.1)
        * Potential destination to keep Silverlight support.

    Profile 111 (.NET 4.5, Windows 8.0, Windows Phone 8.1)
        * UWP support?

    Profile 78 (.NET 4.5, Windows 8.0, Windows Phone Silverlight 8.0)
        * This is the current.

 [ ] Always do "latest" android events so do we do previous API levels?
 [ ] Update Events to use the new xamarin convention (/developer) is deprecated.
 [ ] Implement https://github.com/gsscoder/commandline

# CLI API

EventBuilder.exe  --template Events.mustache [--assemblies string[]]

    -- assemblies[] =
        string array of assemblies to convert event handlers into OPAH

    -- template =
        name of the input template

Default logic is to generate for all platforms that are installed and written
to the filesystem. If --assemblies is specified then that previous behaviour is
not done and result is written to STDOUT.

Error conditions

    - Template is missing.
    - Assemblies passed in do not exist.
    - Assemblies passed in are invalid.
    - Platform is not installed.

# Reactive Events Internals

var targetAssemblyNames = args.TakeWhile(x => !x.EndsWith(".mustache"));
var targetAssemblyDirs = targetAssemblyNames.Select(x => Path.GetDirectoryName(x)).Distinct().ToList();

GenerateEvents.exe
    $1 = string[] "dlls to process"
    $2 = template aka Events.mustache

Will generate class to SDOUT


# Platform Libraries

## Xamarin.Android

Cheap Hacks

    // NB: I'm too lazy to fix this properly
    var monoDroidDir = targetAssemblyDirs.FirstOrDefault(x => x.ToLowerInvariant().Contains("monoandroid"));
    if (monoDroidDir != null) {
        // /Developer/MonoAndroid/lib/mandroid/platforms/android-15 =>
        // /Developer/MonoAndroid/lib/xbuild-frameworks/MonoAndroid/v1.0
        targetAssemblyDirs.Add(Path.Combine(monoDroidDir,
            "..", "..", "..",
            "xbuild-frameworks", "MonoAndroid", "v1.0"));
    }

Windows

    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v4.0.3\Mono.Android.dll
    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v4.0.3\Mono.Android.Support.v13.dll

Mac

    /Library/Frameworks/Xamarin.Android.framework

    lrwxr-xr-x 1 root wheel  20 Nov 19 22:51 Libraries -> Versions/Current/lib/
    lrwxr-xr-x 1 root wheel  20 Nov 19 22:51 Commands -> Versions/Current/bin/
    drwxr-xr-x 6 root wheel 204 Nov 19 22:51 Versions/

    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-10/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-15/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-16/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-17/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-18/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-19/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-20/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-21/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-22/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/mandroid/platforms/android-23/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v2.3/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.0.3/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.1/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.2/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.3/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.4/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v4.4.87/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v5.0/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v5.1/Mono.Android.dll
    /Library/Frameworks/Xamarin.Android.framework/Versions/6.0.0-34/lib/xbuild-frameworks/MonoAndroid/v6.0/Mono.Android.dll

## Xamarin.iOS


Windows

    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Xamarin.iOS.dll

Mac

    /Library/Frameworks/Xamarin.iOS.framework/Versions
    total 4
    lrwxr-xr-x  1 ghuntley staff   7 Jan 15 22:37 Current -> 9.4.0.0/
    drwxr-xr-x 13 ghuntley staff 442 Jan 15 22:37 9.4.0.0/

    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current
    ./lib/32bits/Xamarin.iOS.dll
    ./lib/64bits/Xamarin.iOS.dll
    ./lib/mono/Xamarin.iOS/Xamarin.iOS.dll

    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll


## Xamarin.Mac

Cheap Hacks

    // NB: Double down on Laziness
    var xamMacDir = targetAssemblyDirs.FirstOrDefault(x => x.ToLowerInvariant().Contains("xamarin.mac"));
    if (xamMacDir != null) {
        targetAssemblyDirs.Add("/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5");
    }

Mac

    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/XamMac.dll

## Xamarin Forms

Mac

    ../packages/Xamarin.Forms.1.4.2.6359/lib/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10/Xamarin.Forms.Core.dll

    targetAssemblyDirs.Add("/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/.NETPortable/v4.5/Profile/Profile78");

Windows


Cheap Hacks

    // NB: Triple down on Laziness
    if (targetAssemblyNames.Any(x => x.ToLowerInvariant().Contains("xamarin.forms"))) {
        targetAssemblyDirs.Add("/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/.NETPortable/v4.5/Profile/Profile78");
    }

## Windows Forms

## Windows RT

Cheap Hacks

    // NB: This hacks WinRT's weird mscorlib to just use the regular one
    if (fullName.Contains("mscorlib") && fullName.Contains("255"))
    {
        fullPath = Environment.ExpandEnvironmentVariables(@"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll");
    }

## Windows Store

    https://gist.github.com/ghuntley/0ff7d006d5002391ec21

## Windows Presentation Framework

    https://gist.github.com/ghuntley/0ff7d006d5002391ec21

## Windows Universal

    https://gist.github.com/ghuntley/0ff7d006d5002391ec21

# CI Workflow
[ ] Install Xamarin licenses onto build host


[ ] Always build EventBuilder.csproj

    at Geoffreys-MacBook-Pro.local in ReactiveUI.Events/ on rxui7-master
    › xam EventBuilder.csproj

    at Geoffreys-MacBook-Pro.local in ReactiveUI.Events/ on rxui7-master
    › find . -name "*.exe"
    ./bin/Release/EventBuilder.exe
    ./obj/Release/EventBuilder.exe

[ ] Run result of EventBuilder to generate classes needed per platform
[ ] Run $perPlatform csproj to generate class library
[ ] Package resulting workflow
[ ] Uninstall Xamarin licenses from build host.

**Comment by martingemme** [comment]
Will there be a project elsewhere to use thoses extensions (that I love) after 7.0 release?

**Comment by ghuntley** [comment]
`this.Events()` aka ReactiveUI-events still exists after v7.0.

This is an internal reorganization on how the events will be generated at package/compile time.

`EventBuilder.exe` has been moved into https://github.com/reactiveui/ReactiveUI/tree/rxui7-master/EventBuilder

**Comment by martingemme** [comment]
:+1: cool! I'll try it after 7.0 release with SyncFusion's controls. Thanks!
